---
dependencies:
- appliesTo:  ALL
  groupId:    org.mule.connectors
  artifactId: mule-sockets-connector
  version:    1.2.3
- appliesTo:  SOLACE
  groupId:    com.solace.connector
  artifactId: solace-mulesoft-connector
  version:    1.3.1
- appliesTo:  XML_MODULE
  groupId:    org.mule.modules
  artifactId: mule-xml-module
  version:    1.4.1
- appliesTo:  JSON_MODULE
  groupId:    org.mule.modules
  artifactId: mule-json-module
  version:    2.4.2
- appliesTo:  ALL
  groupId:    org.mule.modules
  artifactId: mule-http-module
  version:    1.8.1
- appliesTo:  ALL
  groupId:    org.mule.modules
  artifactId: mule-java-module
  version:    1.2.11
repositories:
- id:   anypoint-exchange-v3
  name: Anypoint Exchange
  url:  https://maven.anypoint.mulesoft.com/api/v3/maven
- id:   mulesoft-releases
  name: MuleSoft Releases Repository
  url:  https://repository.mulesoft.org/releases/
- id:   mulesoft-releases
  name: MuleSoft Releases Repository
  url:  https://repository.mulesoft.org/releases/
  pluginRepository: true
